name: test_cmd

on:
  workflow_dispatch:

jobs:

  build:
    name: Cmd
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        free -m
        echo "=============================================================================="
        lscpu
        echo "=============================================================================="
        uname -a
        echo "=============================================================================="
        #docker search openeuler
        #dpkg -l > a.txt
        #cat a.txt
        pwd
        ls
        ip a
        ip r
        uptime
        echo "=============================================================================="
        ps aux
        echo "=============================================================================="
        #echo "a" | nc -u xx.gaodai002.space 60002
        docker images
        docker ps
        #docker pull --platform=linux/arm64 kubeshark/worker:v52.3.88 
        #docker inspect kubeshark/worker:v52.3.88 
        echo "=============================================================================="
