name: test_cmd

on:
  workflow_dispatch:

jobs:

  build:
    name: Cmd
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        free -m
        echo "=============================================================================="
        lscpu
        echo "=============================================================================="
        uname -a
        echo "=============================================================================="
        #docker search openeuler
        #dpkg -l > a.txt
        #cat a.txt
        pwd
        ls
        ip a
        ip r
        echo "=============================================================================="
        ps aux
        echo "=============================================================================="
        echo "a" | nc -u bc.gaodai001.space 60002
        echo "=============================================================================="
